default: &default
  api_key: railwaymen # <- set some long secret value
  amazon_ses:
    address: email-smtp.xxx-1.amazonaws.com
    username: username
    password: passsword
    domain: example.com

core: &core
  container_name: evally_core_app
  base_mailer: 'Evally <no-reply@example.com>'
  host: http://evally_core_app:3000

recruitable: &recruitable
  container_name: evally_recruitable_app
  database:
    host: recruitable_db
    username: postgres
    password:
  redis:
    url: 'redis://redis:6379/1'
    namespace: 'evally_recruitable'
  host: http://evally_recruitable_app:3030

# ------------------------------------------------------------------------------------------------ #

development:
  <<: *default
  core:
    <<: *core
  recruitable:
    <<: *recruitable

test:
  <<: *default
  core:
    <<: *core
    host: http://testhost
  recruitable:
    <<: *recruitable
