default: &default
  evally_api_key: railwaymen
  database:
    host: localhost
    username: postgres
    password:

development:
  <<: *default
  core_host: localhost:3000
  self_host: localhost:3030


test:
  <<: *default
  core_host: app.test
  self_host: recruitable.test
